export const S = {
  appName: 'ShoutMate',
  appTagline: 'ShoutMate · Split costs, not friendships.',
  heroHeading: 'Trips sorted.<br/>Mates still mates.',
  heroSub1: 'Track shared expenses as you go and settle up in seconds.',
  heroSub2: 'No accounts. No awkward money chats. Just a fair shout.',
  newTrip: 'New trip',
  yourTrips: 'Your trips',
  noTripsYet: 'No trips yet. Create your first one above!',
  errorTripNameRequired: 'Please enter a trip name.',
  backToTrips: '← Back to trips',
  shareBtn: '🔗 Share',
  shareCopied: 'Share link copied to clipboard!',
  clickToRename: 'Click to rename',
  noOneYet: 'No one added yet. Start by adding your group.',
  errorNameRequired: 'Please enter a name.',
  errorNameDuplicate: 'That name is already in the group.',
  confirmRemovePerson: (name: string) => `Remove ${name}? Any expenses they paid will also be removed.`,
  selectPerson: 'Select person',
  noExpensesYet: 'No expenses yet. Add your first one above.',
  expensesTitle: 'Expenses',
  paidBy: 'Paid by',
  split: 'Split:',
  perPersonSuffix: '/person',
  errorDescRequired: 'Please enter a description.',
  errorAmountInvalid: 'Please enter a valid amount greater than zero.',
  errorPaidByRequired: 'Please select who paid.',
  errorSplitRequired: 'Please select at least one person to split among.',
  settleNoPeople: 'Add people and expenses to see how to settle up.',
  settleNoExpenses: 'No expenses logged yet. Add some expenses first.',
  summaryTitle: 'Summary',
  paymentsTitle: 'Payments to make',
  settledUp: 'Everyone is settled up!',
  isOwed: (amt: string) => `is owed ${amt}`,
  owes: (amt: string) => `owes ${amt}`,
  isSettledUp: 'is settled up',
  settled: 'settled',
  pays: 'pays',
  tripInvite: 'Trip invite',
  saveToMyTrips: 'Save to my trips',
  goToMyTrips: 'Go to my trips',
  invalidShareLink: 'Invalid share link.',
  total: 'total',
  currencyLabel: 'Currency',
  lightMode: '☀️',
  darkMode: '🌙',
  confirmDeleteTrip: (name: string) => `Delete "${name}"? This cannot be undone.`,
  group: (count: number) => `Group (${count})`,
  person: 'person',
  people: 'people',
  expense: 'expense',
  expenses: 'expenses',
  created: 'Created',
};
